{% set name = "crowsetta" %}
{% set version = "5.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crowsetta-{{ version }}.tar.gz
  sha256: 52c42c61d314e0279f69fa00789a2937d503350e6acaba63e80b4200346684a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - flit-core
  run:
    - appdirs >=1.4.4
    - attrs >=19.3.0
    - importlib-resources >=5.7.1
    - numpy >=1.22.0
    - pandas >=1.4.0
    - pandera >=0.9.0
    - python >=3.10
    - scipy >=1.8.0
    - pysoundfile >=0.12.1

test:
  imports:
    - crowsetta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/crowsetta/
  summary: A Python tool to work with any format for annotating animal vocalizations and bioacoustics data
  dev_url: https://github.com/vocalpy/crowsetta
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
