{% set python_min = '3.10' %}
{% set name = "crowsetta" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crowsetta-{{ version }}.tar.gz
  sha256: dec216936b19e89773f9386d131027ba405b517d3f99fb11b665f74b589c67e0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - appdirs >=1.4.4
    - attrs >=19.3.0
    - importlib-resources >=5.7.1
    - numpy >=1.22.0
    - pandas >=1.4.0
    - pandera >=0.9.0
    - python >={{ python_min }}
    - scipy >=1.8.0
    - pysoundfile >=0.12.1

test:
  imports:
    - crowsetta
  commands:
    - pip check
  requires:
    # place temporary upper bound on pip so pip check does not fail on soundfile
    # see https://github.com/conda-forge/pysoundfile-feedstock/issues/22
    - pip <24.2
    - python {{ python_min }}

about:
  home: https://pypi.org/project/crowsetta/
  summary: A Python tool to work with any format for annotating animal vocalizations and bioacoustics data
  dev_url: https://github.com/vocalpy/crowsetta
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
