{% set name = "crowsetta" %}
{% set version = "5.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crowsetta-{{ version }}.tar.gz
  sha256: 3220bf33a6fbe4eed0216259877b64c52d256526052d9712712f5576d21a1e2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core
  run:
    - appdirs >=1.4.4
    - attrs >=19.3.0
    - birdsong-recognition-dataset >=0.3.2
    - evfuncs >=0.3.5
    - importlib-resources >=5.7.1
    - numpy >=1.21.0
    - pandas >=1.3.5
    - pandera >=0.9.0
    - python >=3.9
    - scipy >=1.7.0
    - pysoundfile >=0.12.1

test:
  imports:
    - crowsetta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/crowsetta/
  summary: A Python tool to work with any format for annotating animal vocalizations and bioacoustics data
  dev_url: https://github.com/vocalpy/crowsetta
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
